# This file was generated by GoReleaser. DO NOT EDIT.
cask "vex" do
  version "0.0.33"

  on_macos do
    on_intel do
      sha256 "0e592954033ebebc30b7955d774be0dc2a261815d56a3d05d97b66c3a317648c"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b14d4d63ef36c388fa8a2d6e748cba912bea02cb36c48f3e4475846df31f003e"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ab5dd1d451a515bab0b1a2c676e684c2367ebbef4943000f2abcaa52262a3cd"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f604a5b732c5ca25e179e0f87b37bc021b8ca62c5400a2f87d6d93e7d095c1bc"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_linux_arm64.tar.gz"
    end
  end

  name "vex"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vex"

  # No zap stanza required

end
