# This file was generated by GoReleaser. DO NOT EDIT.
cask "vex" do
  version "0.0.30"

  on_macos do
    on_intel do
      sha256 "20aa4d895a4b5e4282f6e12503278424ce526235c436d40b021c922717f8998e"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4f4838b216a0600fd557fbffea7a1c23b38d7fec210de02f4e23371f3ecf996"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e234d6ca4230b983bacc9d2c812e42d2da2a607cd7f2a3cd9a2d4ddc87449bd9"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c8e52407d71b985008886c3e205790a3af48e121f3dd5065e47346bea8ccd65"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_linux_arm64.tar.gz"
    end
  end

  name "vex"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vex"

  # No zap stanza required

end
