# This file was generated by GoReleaser. DO NOT EDIT.
cask "vex" do
  version "0.0.29"

  on_macos do
    on_intel do
      sha256 "47b64666b699ff663df71fc451f8b31b01e4010c686774924ec51dc0a07bb418"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "36e8e9dd83c5f896d65529ed6e9687641a1eb1fcefa4a00f087aca2b704ef8be"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "029533765ba31e14cf491e7529c9c3a47a016e506d49c33e9d719e41ecb7454f"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8db1d1e73b66067bb27c458c527e0af3b5c365c3359d7183c318e79194ff5c69"
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vex_linux_arm64.tar.gz"
    end
  end

  name "vex"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vex"

  # No zap stanza required

end
