# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexc" do
  name "vexc"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex"
  version "1.0.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexc"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_darwin_amd64.tar.gz"
      sha256 "bdef9b8ebf332197186f75856b8737079aa533eb8f25f3eae6426d1a5b76fa67"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_darwin_arm64.tar.gz"
      sha256 "b13fee40e5ee3522be924a07acb740c73670ad2c1b8f972da180e7bd466f7e1a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_linux_amd64.tar.gz"
      sha256 "bad184ec34bbb236b1ae14acb6b4f8532cc29153f94662a39a3fe1962d08141d"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_linux_arm64.tar.gz"
      sha256 "499f332d1dcef2c53cca947e4ce3468da8aae9671b4c4648e13abf1ad3001ff0"
    end
  end

  # No zap stanza required
end
